[project]
name = "legemara"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "airtest>=1.3.5",
    "loguru>=0.7.3",
    "numpy>=1.26.4",
    "pydantic>=2.10.6",
    "pydantic-settings>=2.8.1",
    "pytest>=8.3.5",
]
